kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-ee-kubernetes
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: java-ee-kubernetes
  template:
    metadata:
      labels:
        app: java-ee-kubernetes
    spec:
      containers:
        - name: java-ee-kubernetes
          image: localhost:5000/java-ee-kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: java-ee-kubernetes
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: java-ee-kubernetes
